### ISSUE TITLE
消息监听全寄了

### ISSUE THREAD

**Issue by CUZNIL** [yeyang52/yenai-plugin#1]
![4EK5~52MJ(CX(UN_9R6O W8](https://user-images.githubusercontent.com/76582404/196641912-3719a016-9136-4cda-b9d8-77f4872b7d16.png)
这些功能都寄了 开启以后无法发消息到我的账号
![image](https://user-images.githubusercontent.com/76582404/196641988-a4c44db9-544d-42f0-af62-c9b851d978ab.png)
这是小号设置
![IYJ$49HJFB~ ZWMMEH53N5R](https://user-images.githubusercontent.com/76582404/196642029-6340a77c-7cbe-4f79-ae52-9adc6d5352a4.gif)
这是表明已经是最新版本

**Comment by yeyang52** [comment]
请添加好友带上日志

**Comment by CUZNIL** [comment]
> 请添加好友带上日志
是指QQ吗 好的
