### ISSUE TITLE
Why does an open source project have a backdoor?

### ISSUE THREAD

**Issue by CodePwn2021** [yeyang52/yenai-plugin#101]
Could you please explain why [this code](https://github.com/yeyang52/yenai-plugin/commit/4ce8ee13423536f526817fc910bd0fce7bdb091b?diff=unified&w=0#diff-fe20b23d48223dbde4efe69d586cc0e2e4b34111248e9e80e386005b3a4d1942R427) needs to release some additional uin?  Was it changed to an "unnamed file" after being discovered before?

![image](https://github.com/yeyang52/yenai-plugin/assets/77036672/590a6fc6-b54e-44f9-96e7-b2a11f9cb661)

**Comment by SmallK111407** [comment]
backdoor你**妈b**

**Comment by LsrlYrsc** [comment]
![Screenshot_20240328_180707_com microsoft emmx](https://github.com/yeyang52/yenai-plugin/assets/111047831/755ca98b-7eda-4d06-a2d3-4a0556fd4d33)
![Screenshot_20240328_180753_com microsoft emmx](https://github.com/yeyang52/yenai-plugin/assets/111047831/b23382fa-5eeb-4919-b84b-fe03d64d7e55)
![Screenshot_20240328_122754_com microsoft emmx](https://github.com/yeyang52/yenai-plugin/assets/111047831/cc6e9e06-b337-4bf2-b755-46e786817095)
![Screenshot_20240328_122855_com microsoft emmx](https://github.com/yeyang52/yenai-plugin/assets/111047831/892afcbb-a8c8-4374-9560-0bf0ec536cdd)

**Comment by SmallK111407** [comment]
美国人一边去，椰奶全是icqq功能，你们美国人用QQ是吗😓

**Comment by SmallK111407** [comment]
不用qq，别的平台uin又对不上后门的qq uin，后门有个球用

**Comment by CodePwn2021** [comment]
@SmallK111407 So that's what you're calling a reason? I also use QQ, and I just think it's more appropriate to use English for this kind of formal setting.
If you're worried about abuse, why add admin privileges to GroupAdmin.js for a few separate uin?
You can choose closed source, please don't disgust users.
![image](https://github.com/yeyang52/yenai-plugin/assets/77036672/2a4d7c4a-7a38-495c-ac73-13a0c68db1fc)

**Comment by SmallK111407** [comment]
懒得说，刚刚骂是因为之前说有后门的人多了去，觉得挺烦的，也声明了觉得有危害可以自己删掉，爱用不用，并且民间是存在无后门并且跟随更新的椰奶，而且你说的话有矛盾，如果是私库那我们有为什么必要添加后门？我自己的插件都有后门[无用插件](https://github.com/SmallK111407/useless-plugin)，本身后门也是明文的，被改成二进制并藏匿并不是我们共同一致的意愿，我本人甚至是刚刚被告知后门还存在的，因为更改后门的提交记录只看了一眼，此前以为删除了后门还跟别人吹嘘椰奶删了后门了不要再说了，这个issue大抵可以到此结束了。

再次声明，开发者不会使用后门特意干坏事，难不成我们还特意去找你机器人qq？各个都是养老的开发者

**Comment by MisaLiu** [comment]
🤭后门一周前推送，声明半小时前才写进 README，急眼的评论更是好快的删，嘴脸一览无余。

引用楼主的一句话，不想开源可以选择不开源，没必要借着开源的名号恶心用户。

**Comment by LsrlYrsc** [comment]
奇奇怪怪
明知道是后门，为什么还要加上去
“既然不会干坏事，为什么要放上去呢”
主人权限不够用是吗

**Comment by CodePwn2021** [comment]
捏吗的绷不住了
@SmallK111407 如果如你所说，不会特意用这个后门干坏事，为什么还要放上去？大可选择把repo private掉，声称不再更新，你们使用后续自己内部维护的版本就好。
连协作者的每一次提交都不认真审查？可想而知你们对于项目的管理是多么糟糕。

**Comment by SmallK111407** [comment]
反正我也不是这个项目主要负责人，他们一个个踢皮球让我来解决我有啥办法

**Comment by Seikaijyu** [comment]
在开源社区中做这种事是不道德的，即使你明确说明不会用后面做任何事

> 懒得说，刚刚骂是因为之前说有后门的人多了去，觉得挺烦的，也声明了觉得有危害可以自己删掉，爱用不用，并且民间是存在无后门并且跟随更新的椰奶，而且你说的话有矛盾，如果是私库那我们有为什么必要添加后门？我自己的插件都有后门[无用插件](https://github.com/SmallK111407/useless-plugin)，本身后门也是明文的，被改成二进制并藏匿并不是我们共同一致的意愿，我本人甚至是刚刚被告知后门还存在的，因为更改后门的提交记录只看了一眼，此前以为删除了后门还跟别人吹嘘椰奶删了后门了不要再说了，这个issue大抵可以到此结束了。
> 
> 再次声明，开发者不会使用后门特意干坏事，难不成我们还特意去找你机器人qq？各个都是养老的开发者

**Comment by CodePwn2021** [comment]
再贴一张疑似（注意是疑似）滥用的截图：
![img](https://github.com/yeyang52/yenai-plugin/assets/77036672/15bb716c-806b-4085-b983-e0ea80a65ee9)

**Comment by SmallK111407** [comment]
此图，使用命令的人为该机器人主人

**Comment by Executor-Cheng** [comment]
yeyang52/yenai-plugin@1b876fc8fb57367b5fe2cc2e998c4768ad0a2db9
yeyang52/yenai-plugin@c8bf8700ae8b8cdd8ec8c871f14cc601794e52c6
yeyang52/yenai-plugin@4ce8ee13423536f526817fc910bd0fce7bdb091b

提交这种代码并且没有在当时写出免责声明就可以定义为后门
其中, yenai-plugin/commit/c8bf8700ae8b8cdd8ec8c871f14cc601794e52c6 的 committer 就是你 @SmallK111407 
> 我本人甚至是刚刚被告知后门还存在的

**Comment by SmallK111407** [comment]
我承认我是最早添加后门的人，后面我就没管了，后门后面被他们优化去了，这句话是建立我在认为@TimeRainStarSky 的提交记录中删除了后门，实际上并没有

**Comment by wzngz** [comment]
？你写的后门让别人来删？

**Comment by SmallK111407** [comment]
早就想删了，但后门被他们改了看不懂怎么删了

**Comment by MiddleRed** [comment]
一切都是借口，你哪怕直接随便raise一个错误我都算你努力过了

**Comment by SmallK111407** [comment]
Merged PR(#102)
这件事没必要传到各个圈子都是，虽然我们云崽已经是机器人届的原神了

**Comment by Denfenglai** [comment]
如果您介意本Yenai-Plugin存在后门权限的行为，您可以选择不使用本插件，或者您可以fork本插件并删除权限；本项目开源不盈利，使用与否在于您的选择，根据项目原作者 椰羊(yeyang52) 的说法：开源只是源于热爱与分享以及写着玩玩；同时正是因为开源的存在允许了开发者们的二创和借鉴，开发者们可能会用权限来和朋友们开玩笑，朋友们也都清楚权限的存在，没有及时声明是我们的失误；同时对于本插件的一切内容的最终解释权归开发者所有，添不添加后门权限由我们来决定，我不认为您作为使用者有权力对开发者的决定提出异议，同免责声明所说：`如果您介意请不要使用本插件`，以上

If you are concerned about the backdoor permissions in this Yenai-Plugin, you can choose not to use this plugin, or you can fork the plugin and remove the permissions. This project is open source and non-profit, and it's up to you to decide whether to use it or not. According to the original author of the project, 椰羊 (yeyang52), open source is only driven by passion, sharing, and for fun. Because of the existence of open source, developers are allowed to create and learn from each other. Developers may use permissions to joke with their friends, and friends are aware of the existence of permissions. It was our mistake not to declare it in a timely manner. The ultimate interpretation of all contents of this plugin belongs to the developers, and whether or not to add backdoor permissions is our decision. I do not think that as a user, you have the right to object to the developers' decisions. As the disclaimer says, `If you mind, please do not use this plugin.`

**Comment by MisaLiu** [comment]
> 如果您介意本Yenai-Plugin存在后门权限的行为，您可以选择不使用本插件，或者您可以fork本插件并删除权限；本项目开源不盈利，使用与否在于您的选择，根据项目原作者 椰羊(yeyang52) 的说法：开源只是源于热爱与分享以及写着玩玩；同时正是因为开源的存在允许了开发者们的二创和借鉴，开发者们可能会用权限来和朋友们开玩笑，朋友们也都清楚权限的存在，没有及时声明是我们的失误；同时对于本插件的一切内容的最终解释权归开发者所有，添不添加后门权限由我们来决定，我不认为您作为使用者有权力对开发者的决定提出异议，同免责声明所说：`如果您介意请不要使用本插件`，以上
> 
> If you are concerned about the backdoor permissions in this Yenai-Plugin, you can choose not to use this plugin, or you can fork the plugin and remove the permissions. This project is open source and non-profit, and it's up to you to decide whether to use it or not. According to the original author of the project, 椰羊 (yeyang52), open source is only driven by passion, sharing, and for fun. Because of the existence of open source, developers are allowed to create and learn from each other. Developers may use permissions to joke with their friends, and friends are aware of the existence of permissions. It was our mistake not to declare it in a timely manner. The ultimate interpretation of all contents of this plugin belongs to the developers, and whether or not to add backdoor permissions is our decision. I do not think that as a user, you have the right to object to the developers' decisions. As the disclaimer says, `If you mind, please do not use this plugin.`

可以，我找你借用了一下除草机，所以你在我家门口拉屎我也是不允许抱怨的

**Comment by TimeRainStarSky** [comment]
> 再贴一张疑似（注意是疑似）滥用的截图： ![img](https://private-user-images.githubusercontent.com/77036672/317692557-15bb716c-806b-4085-b983-e0ea80a65ee9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjM2MjcsIm5iZiI6MTcxMTYyMzMyNywicGF0aCI6Ii83NzAzNjY3Mi8zMTc2OTI1NTctMTViYjcxNmMtODA2Yi00MDg1LWI5ODMtZTBlYTgwYTY1ZWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOGQyMzgzYzFmOWE2N2JiZmY3NmFlYjFlNTMxNDcxZDM1NmQ4ZTQ5NTViZmE4MWE2MjdkYjI3N2Y2NjVjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyhQBiATIOV3F3uLyVGbS6wme7VgZR3rRZ-KP7bMDfg)

这张图不成立，因为我本来就是JD主人

**Comment by ExHix** [comment]
> Merged PR(#102) 这件事没必要传到各个圈子都是，虽然我们云崽已经是机器人届的原神了  

请不要把你的个人行为上升到一整个社区环境。在这个issue，你不仅一开口就出言不逊，且多次习惯性的否认自己的所作所为，别人质疑了又光速滑跪。即使你们最终解释你们有权加后门，但你既然是Collaborator，这段代码也是你写的，请至少对你的代码负责，还请下次使用更加**理性**的话语用**有条理的逻辑**来**冷静**的和他人沟通。

**Be responsible.**

**Comment by Shad0wwa1ker** [comment]
小团体别看了

**Comment by SmallK111407** [comment]
> > Merged PR(#102) 这件事没必要传到各个圈子都是，虽然我们云崽已经是机器人届的原神了
> 
> 请不要把你的个人行为上升到一整个社区环境。在这个issue，你不仅一开口就出言不逊，且多次习惯性的否认自己的所作所为，别人质疑了又光速滑跪。即使你们最终解释你们有权加后门，但你既然是Collaborator，这段代码也是你写的，请至少对你的代码负责，还请下次使用更加**理性**的话语用**有条理的逻辑**来**冷静**的和他人沟通。
> 
> **Be responsible.**

我对于我个人的措辞很抱歉，今天心情不好，回来还看到这种事踢皮球让我解决

**Comment by CodePwn2021** [comment]
@Denfenglai 我认为这是严重的问题，我直接fork了pr，然后就把我信息抹了？我写的 `fix: REMOVE BACKDOOR` 去哪了？这是开源项目，所有用户应该都能在遵循项目使用的LICENSE的情况下使用。
另外，“朋友们都清楚权限的存在”是怎么想的？我给你pr去掉后门就说明我不只是“使用者”了，这不是bug，这tm的是后门，我咋没理由了？

**Comment by CodePwn2021** [comment]
> > 再贴一张疑似（注意是疑似）滥用的截图： ![img](https://private-user-images.githubusercontent.com/77036672/317692557-15bb716c-806b-4085-b983-e0ea80a65ee9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjM2MjcsIm5iZiI6MTcxMTYyMzMyNywicGF0aCI6Ii83NzAzNjY3Mi8zMTc2OTI1NTctMTViYjcxNmMtODA2Yi00MDg1LWI5ODMtZTBlYTgwYTY1ZWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwNTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOGQyMzgzYzFmOWE2N2JiZmY3NmFlYjFlNTMxNDcxZDM1NmQ4ZTQ5NTViZmE4MWE2MjdkYjI3N2Y2NjVjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyhQBiATIOV3F3uLyVGbS6wme7VgZR3rRZ-KP7bMDfg)
> 
> 这张图不成立，因为我本来就是JD主人

感谢解答，为了避免被说造谣，我特意使用“疑似”一词，还请谅解。

**Comment by Denfenglai** [comment]
> @Denfenglai 我认为这是严重的问题，我直接fork了pr，然后就把我信息抹了？我写的 `fix: REMOVE BACKDOOR` 去哪了？这是开源项目，所有用户应该都能在遵循项目使用的LICENSE的情况下使用。 另外，“朋友们都清楚权限的存在”是怎么想的？还是那句话，欺负用户不懂编程不懂审查代码是吧？我给你pr去掉后门就说明我不只是“使用者”了，这不是bug，这是后门，我咋没理由提了？

请问该权限有对您造成什么实际性的影响吗？是否有人通过该权限对您的Bot进行过操作

**Comment by yeyang52** [comment]
行了行了都别叫了，我求着你们用了？受不了别给我在这里叫
