### ISSUE TITLE
[补档] Why does an open source project have a backdoor?

### ISSUE THREAD

**Issue by Wesley-Young** [yeyang52/yenai-plugin#103]
行了行了都别叫了，我求着你们用了？受不了别给我在这里叫

**Comment by CodePwn2021** [comment]
支持补档

**Comment by yeyang52** [comment]
支持

**Comment by 8852690** [comment]
前排吃瓜

**Comment by CodePwn2021** [comment]
怎么会是呢？
![image](https://github.com/yeyang52/yenai-plugin/assets/77036672/cd31ac49-9db9-4d59-a227-0e770e7715b0)

**Comment by yeyang52** [comment]
@Wesley-Young @CodePwn2021 Please continue with your performance.

**Comment by TangTangawa** [comment]
![image](https://github.com/yeyang52/yenai-plugin/assets/67052443/071babe4-2272-40c1-ae92-ec61bd17dadb)

**Comment by CodePwn2021** [comment]
> @Wesley-Young @CodePwn2021 Please continue with your performance.

The pathetic circus clown thinks that deleting the issue will cover everything up.

**Comment by Wesley-Young** [comment]
<img width="938" alt="image" src="https://github.com/yeyang52/yenai-plugin/assets/25684570/c1578cf0-f1b4-4a84-95c5-fb2a60c7b807">
It seems that after editing the original picture is still visible. So if you want to completely "control" the whole mess, just apologize.

**Comment by TangTangawa** [comment]
怎么会事呢
![image](https://github.com/yeyang52/yenai-plugin/assets/67052443/84fbb2de-7757-4a91-bc3b-eed17d3450dc)

**Comment by yeyang52** [comment]
> > 请继续您的表演。
> 
> 可怜的马戏团小丑认为删除问题会掩盖一切。

对，然后呢？

**Comment by Tbl0x7D6** [comment]
憋笑

**Comment by shealligh** [comment]
憋不不憋

**Comment by Wesley-Young** [comment]
> > > 请继续您的表演。
> > 
> > 
> > 可怜的马戏团小丑认为删除问题会掩盖一切。
> 
> 对，然后呢？

找不到话说了，恳求对方再骂两句？

**Comment by Gintamashiichan** [comment]
Since notepad++, we had the common sense that adding backdoors to your code is unethical and may violate the GitHub ToS.

**Comment by yeyang52** [comment]
> > > > 请继续您的表演。
> > > 
> > > 
> > > 可怜的马戏团小丑认为删除问题会掩盖一切。
> > 
> > 
> > 对，然后呢？
> 
> 找不到话说了，恳求对方再骂两句？

支持

**Comment by yeyang52** [comment]
> Since notepad++, we had the common sense that adding backdoors to your code is unethical and may violate the GitHub ToS.

支持👍

**Comment by CodePwn2021** [comment]
憋笑

**Comment by TangTangawa** [comment]
:D

**Comment by KujoStar** [comment]
玩原神玩的

**Comment by yeyang52** [comment]
少玩原神

**Comment by CodePwn2021** [comment]
还好我不玩原神

**Comment by yeyang52** [comment]
> 还好我不玩原神

玩原神玩的
