### ISSUE TITLE
建议不要硬编码后门

### ISSUE THREAD

**Issue by cc004** [yeyang52/yenai-plugin#104]
**问题描述**
希望给后门加一个配置 方便这个qq号被封之后修改为新的号

**实现方式**
用backdoor.json配置后门 如果可以支持多qq更好

**当前的问题**
参见问题描述

**Comment by cca2878** [comment]
支持，机器人的控制权必须牢牢捏在维护者手里。

**Comment by yeyang52** [comment]
支持，尽快pr

**Comment by CodePwn2021** [comment]
支持，尽快pr

**Comment by xBoyMinemc** [comment]
致辞，巾块泡水膨胀变大
