### ISSUE TITLE
修改群名

### ISSUE THREAD

**Issue by A-Kevin1217** [yeyang52/yenai-plugin#111]
建议添加修改群名功能

**Comment by Denfenglai** [comment]
#改群昵称

**Comment by A-Kevin1217** [comment]
不是群昵称，是群的名字，例如xxxx群，而不是机器人在群里的名字

**Comment by Denfenglai** [comment]
> 不是群昵称，是群的名字，例如xxxx群，而不是机器人在群里的名字 

![Image_1712896902497](https://github.com/yeyang52/yenai-plugin/assets/129082426/3e9809fe-8b0a-4ae3-b1ad-83720f2e78f4)
试了再说，再问紫砂

**Comment by yeyang52** [comment]
https://yenai.trss.me/features/Assistant.html#%E6%94%B9%E6%80%A7%E5%88%AB

**Comment by A-Kevin1217** [comment]
> > 不是群昵称，是群的名字，例如xxxx群，而不是机器人在群里的名字 
> 
> 
> 
> ![Image_1712896902497](https://github.com/yeyang52/yenai-plugin/assets/129082426/3e9809fe-8b0a-4ae3-b1ad-83720f2e78f4)
> 
> 试了再说，再问紫砂

骚瑞，群昵称这个叫法 属实是有点迷
