### ISSUE TITLE
建议新增一个艾特全体的功能

### ISSUE THREAD

**Issue by A-Kevin1217** [yeyang52/yenai-plugin#114]
**问题描述**
希望机器人发送可以艾特全体的功能，并可以自定义艾特全体后面的消息内容，实现群内只有机器人是群主或管理员也能做到艾特全体

**实现方式**
at:all（.*）
⬆️瞎写的

**Comment by yeyang52** [comment]
#发通知

**Comment by Denfenglai** [comment]
不看文档导致的
[文档](https://yenai.trss.me)
