### ISSUE TITLE
一点关于使用qqnt发送消息的问题

### ISSUE THREAD

**Issue by kldhsh123** [yeyang52/yenai-plugin#115]
当使用qqnt发送消息时，会出现一些很奇怪的现象
例如进群验证，机器人发送临时会话消息会跳出发送失败，请加对方为好友，后续的消息也会跳
但是如果你是主动使用qqnt界面向群员发送临时会话，就可以正常发送
这种问题有什么解决办法吗

**Comment by yeyang52** [comment]
是否可以提供相关日志？

**Comment by kldhsh123** [comment]
[MiaoYz][15:47:28.198][ERRO] [3751937551] message/send 请求超时，请检查账号状态或重启QQ！请求参数：{"peer":{"chatType":1,"peerUin":"1580516858"},"elements":[{"elementType":1,"textElement":{"content":"✅ 验证成功，欢迎入群"}}]}

**Comment by kldhsh123** [comment]
emmm可以加个验证成功消息在群里发送吗，这样就不用管临时会话问题了

**Comment by yeyang52** [comment]
验证成功本来就是发送在群里啊不是发送在临时消息

**Comment by kldhsh123** [comment]
啊？我只会发临时消息，是配置问题吗？

**Comment by yeyang52** [comment]
我并没有写临时消息的发送，发送运算验证是发送在群里还是临时？

**Comment by yeyang52** [comment]
![Screenshot_2024-05-04-20-24-29-278_com.tencent.mobileqq.png](https://github.com/yeyang52/yenai-plugin/assets/107110851/22fd1381-131b-4823-ae45-87bab0cb7e6f)

**Comment by kldhsh123** [comment]
我这运算发群里，成功发临时
我重装下插件试试

**Comment by kldhsh123** [comment]
额....
还是一样

**Comment by kldhsh123** [comment]
没事了，有点延迟...
重装之后好了
