### ISSUE TITLE
[功能建议]: 建议新增一个投票踢人功能

### ISSUE THREAD

**Issue by A-Kevin1217** [yeyang52/yenai-plugin#119]
### 问题描述

有些群友很烦人，但作为管理员直接踢掉又不太好

### 实现方式

就是和投票禁言一样的方式

### 意向参与贡献

- [ ] #120

**Comment by Denfenglai** [comment]
不太愿意弄这个功能，个人认为踢人权限太过敏感，有投票禁言功能就行了，另外请说明“管理直接踢不太好”体现在哪里，既然都觉得烦人为何不直接踢掉呢，其次投票顾名思义不需要管理介入，那么出现误踢怨踢的情况下也在所难免，请详细说明该功能的重要性，感谢。

**Comment by A-Kevin1217** [comment]
> 不太愿意弄这个功能，个人认为踢人权限太过敏感，有投票禁言功能就行了，另外请说明“管理直接踢不太好”体现在哪里，既然都觉得烦人为何不直接踢掉呢，其次投票顾名思义不需要管理介入，那么出现误踢怨踢的情况下也在所难免，请详细说明该功能的重要性，感谢。

因为我那个群的群主比较软柿子，不让管理员随随便便把某个人踢掉，即便这个人已经侵犯了个人利益，但群主依然不让把踢掉，所以我觉得有一个投票踢出的功能会比较好一点，如果出现了误踢怨踢的情况可以找群主或管理员去说，重新申请加群也是可以的，也可以给这个功能加一个总开关。如果还是不行的话，那就算了吧

**Comment by A-Kevin1217** [comment]
> > > 不太愿意弄这个功能，个人认为踢人权限太过敏感，有投票禁言功能就行了，另外请说明“管理直接踢不太好”体现在哪里，既然都觉得烦人为何不直接踢掉呢，其次投票顾名思义不需要管理介入，那么出现误踢怨踢的情况下也在所难免，请详细说明该功能的重要性，感谢。
> > 
> > 
> > 因为我那个群的群主比较软柿子，不让管理员随随便便把某个人踢掉，即便这个人已经侵犯了个人利益，但群主依然不让把踢掉，所以我觉得有一个投票踢出的功能会比较好一点，如果出现了误踢怨踢的情况可以找群主或管理员去说，重新申请加群也是可以的，也可以给这个功能加一个总开关。如果还是不行的话，那就算了吧
> 
> 感谢解答，那么既然已经“不让管理员随随便便把某个人踢掉”，机器人踢就没问题了吗？功能可以支持，先前我也想过该功能，只是考虑到实际使用上踢人的权限似乎太过敏感，禁言操作是可逆的，可是踢人会重置群等级、头衔等。功能或将在后续推送中支持，计划基本于`投票禁言`功能保持一致，没有问题吧。

嗯嗯好的，顺便就是解答一下，就是如果是大家都希望踢掉的人，群主是不会说什么的，我那个群的人也是这么想的
