### ISSUE TITLE
「bug」投票踢人的bug

### ISSUE THREAD

**Issue by A-Kevin1217** [yeyang52/yenai-plugin#122]
![image](https://github.com/yeyang52/yenai-plugin/assets/21151999/bc1a79d0-70e3-4ed0-b1c4-4a57193335be)
如图

**Comment by Denfenglai** [comment]
似乎？只是显示错误？请问投票数是否有问题

**Comment by A-Kevin1217** [comment]
> 似乎？只是显示错误？请问投票数是否有问题

最终没达到我设置的最低票数，不太清楚他实际票数有没有问题

**Comment by Denfenglai** [comment]
> > 似乎？只是显示错误？请问投票数是否有问题
> 
> 最终没达到我设置的最低票数，不太清楚他实际票数有没有问题

请问能否提供完整截图

**Comment by A-Kevin1217** [comment]
> > > 似乎？只是显示错误？请问投票数是否有问题
> > 
> > 最终没达到我设置的最低票数，不太清楚他实际票数有没有问题
> 
> 请问能否提供完整截图

![image](https://github.com/yeyang52/yenai-plugin/assets/21151999/89fedcc6-3de7-4348-93cf-7d0a5075e99a)

**Comment by Denfenglai** [comment]
已尝试修改，请测试
