### ISSUE TITLE
[问题反馈]:哔咔搜索返回信息错误 

### ISSUE THREAD

**Issue by lumia1998** [yeyang52/yenai-plugin#123]
### 反馈内容

返回的是一串id不是本子的名字

### 其他说明

![image](https://github.com/yeyang52/yenai-plugin/assets/63107956/45ac8a1b-cc96-4e8e-baf9-423fee58dc0f)

**Comment by yeyang52** [comment]
可以提供一下执行哔咔搜索时的日志吗

**Comment by lumia1998** [comment]
![image](https://github.com/yeyang52/yenai-plugin/assets/63107956/e68e6fd6-e6d5-4d92-8e12-10dae0767900)
![image](https://github.com/yeyang52/yenai-plugin/assets/63107956/54fce436-55f9-4e54-9ecf-afe3194c9598)
使用nanapcat(onebot)对接

**Comment by yeyang52** [comment]
trss的segment.image不支持Readable建议催更trss或者使用icqq

**Comment by lumia1998** [comment]
那请问能否添加个选项不返回图片只返回本子名呢?

**Comment by Denfenglai** [comment]
> 楼上“那请问能否添加个选项不返回图片只返回本子名呢?”
> 
> 同求，哔咔搜索时，如果出现R18图片，将导致合并消息无法发出。能否像“whatanime 得到 R18 结果时隐藏结果缩略图”那样处理一下？或者就添加开关别显示缩略图了

on `yenai-plugin/config/config/bika.yaml`

```yaml
# 隐藏哔咔搜索简略图
hideSearchImg: true # line 16
```
