### ISSUE TITLE
[功能建议]: 还是哔咔相关希望多个是否显示图片的开关

### ISSUE THREAD

**Issue by lumia1998** [yeyang52/yenai-plugin#124]
### 问题描述

哔咔插件支持不返回图片仅返回本子名和tag等信息

### 实现方式

不显示图片

### 当前的问题

返回信息会多出一串id,而且担心图片可能r18会导致qq风控

### 其他说明

**1、 人付き合いが苦手な未亡人の雪女さんと呪いの指輪 [中国翻訳]
作者：ぷぅのぷぅぷぅぷぅ (ぷぅ崎ぷぅ奈)
描述：
感谢金主 杂兵七夜+魂之挽歌+EA+两位匿名绅士 出...
分类：全彩，長篇，人妻，非人類
喜欢：421924
完结：true
tag：全彩,女性主導,雪女,未亡人,劇情,蹦壞臉,榨精,精神...**

比如只返回这种信息

 
![image](https://github.com/yeyang52/yenai-plugin/assets/63107956/05576171-f8b2-4c24-9303-9e738b5cdb29)
mei每个本子前面会有这个信息能删除吗

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献到本插件

**Comment by yeyang52** [comment]
单独发出id是为了方便复制 使用`#哔咔id`即可查看对应本

**Comment by lumia1998** [comment]
> 单独发出id是为了方便复制 使用`#哔咔id`即可查看对应本

那哔咔搜索可以添加个关闭封面图的功能吗

**Comment by Denfenglai** [comment]
> 那哔咔搜索可以添加个关闭封面图的功能吗

上面不是提交了，在**config/bika.yaml**中键入
```yaml
hideSearchImg: true
```
即可

**Comment by lumia1998** [comment]
![image](https://github.com/yeyang52/yenai-plugin/assets/63107956/e689dd38-0adf-44f3-828d-f66e284f96f6)
好像不可以
