### ISSUE TITLE
[bug]：椰奶状态设置为默认后不生效

### ISSUE THREAD

**Issue by JulienZeng** [yeyang52/yenai-plugin#126]
### 这个问题是否已经存在？

- [X] 我已经搜索过[现有的问题](https://gitee.com/yeyang52/yenai-plugin/issues)并未发现相同问题

### Yunzai版本

TRSS-Yunzai

### Node.js版本

v20.14.0

### 协议端名称

ICQQ

### 操作系统

Ubuntu 20.04 LTS

### 复现步骤

1. `#椰奶设置状态开启`
2. `#状态`
3.  出现默认状态

### 预期行为

发送`#状态`回复椰奶状态

### 实际行为

发送默认状态
![QQ_1723604720177](https://github.com/user-attachments/assets/62dc0a36-495e-4eb4-a13e-2c21fbbe7efa)
- 椰奶设置
![e696a25a750d9f7c7a8fdee37451e63c](https://github.com/user-attachments/assets/cb1d4efd-432b-4759-9f6d-378059f44169)

### 错误日志或截图

0|TRSS-Yun | [10:51:09.537][MARK][] ICQQ(QQ) v0.6.10 已连接
0|TRSS-Yun | [10:51:09.539][INFO][Adapter] 加载适配器[7个]
0|TRSS-Yun | [10:51:09.541][INFO][WebSocket] 连接地址：ws://localhost:2536/[ComWeChat,GSUIDCore,OPQBot,OneBotv11,go-cqhttp]
0|TRSS-Yun | [10:51:09.543][MARK][TRSSYz] ----^_^----
0|TRSS-Yun | [10:51:09.821][INFO][] succeed to send: [Private()] [回复]重启成功，用时5.574秒
0|TRSS-Yun | [10:51:13.261][INFO][] recv from: [Private: (friend)] #状态
0|TRSS-Yun | [10:51:13.400][INFO][][#状态][状态统计(status)][开始处理]
0|TRSS-Yun | [10:51:13.886][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yun | [10:51:13.899][MARK][][#状态][状态统计(status)][完成0.496秒]
0|TRSS-Yun | [10:51:22.263][INFO][] recv from: [Private: (friend)] #椰奶设置状态开启
0|TRSS-Yun | [10:51:22.294][INFO][][#椰奶设置状态开启][椰奶配置(ConfigSwitch)][开始处理]
0|TRSS-Yun | [10:51:22.307][INFO][TRSSYz] puppeteer Chromium 启动中...
0|TRSS-Yun | [10:51:22.310][MARK][][#椰奶设置状态开启][椰奶配置(ConfigSwitch)][完成0.013秒]
0|TRSS-Yun | [10:51:22.317][MARK][TRSSYz] [Yenai-Plugin][修改配置文件][config][whole]
0|TRSS-Yun | [10:51:22.814][INFO][TRSSYz] puppeteer Chromium 启动成功 ws://127.0.0.1:37215/devtools/browser/dd7630c7-a5a3-41a0-b45b-1b3a89c90a0f
0|TRSS-Yun | [10:51:26.001][MARK][TRSSYz] [图片生成][yenai-plugin/admin/index][1次] 1165.86KB 3166ms
0|TRSS-Yun | [10:51:26.557][INFO][] succeed to send: [Private()] [图片]
0|TRSS-Yun | [10:51:30.689][INFO][] recv from: [Private: (friend)] #状态
0|TRSS-Yun | [10:51:30.695][INFO][][#状态][状态统计(status)][开始处理]
0|TRSS-Yun | [10:51:31.237][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yun | [10:51:31.239][MARK][][#状态][状态统计(status)][完成0.542秒]
0|TRSS-Yun | [10:51:35.789][INFO][] recv from: [Private: (friend)] #状态pro
0|TRSS-Yun | [10:51:35.810][INFO][][#状态pro][状态统计(status)][开始处理]
0|TRSS-Yun | [10:51:36.359][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yun | [10:51:36.364][MARK][][#状态pro][状态统计(status)][完成0.549秒]
0|TRSS-Yun | [10:53:36.417][INFO][] recv from: [Private: (friend)] #重启
0|TRSS-Yun | [10:53:36.425][INFO][][#重启][进程管理(restart)][开始处理]
0|TRSS-Yun | [10:53:36.745][INFO][] succeed to send: [Private()] 开始重启，本次运行时长2分29.112秒
0|TRSS-Yun | [10:53:36.748][MARK][执行命令] pnpm run restart
0|TRSS-Yun | [10:53:37.782][MARK][exit] TRSS-Yunzai 已停止运行，本次运行时长：2分30.468秒 (130)
0|TRSS-Yun | [10:53:38.622][MARK][TRSSYz] ----^_^----
0|TRSS-Yun | [10:53:38.626][MARK][TRSSYz] TRSS-Yunzai v3.1.3 启动中...
0|TRSS-Yun | [10:53:38.627][MARK][TRSSYz] https://github.com/TimeRainStarSky/Yunzai
0|TRSS-Yun | [10:53:39.244][INFO][TRSSYz] 加载渲染后端 puppeteer
0|TRSS-Yun | [10:53:39.851][INFO][Redis] 正在连接 redis://127.0.0.1:6379/0
0|TRSS-Yun | [10:53:39.864][MARK][Server] 启动 HTTP 服务器 http://[::]:2536
0|TRSS-Yun | [10:53:39.869][INFO][Plugin] -----------
0|TRSS-Yun | [10:53:39.870][INFO][Plugin] 加载插件中...
0|TRSS-Yun | [10:53:39.937][INFO][TRSSYz] - 正在加载 ICQQ 适配器插件
0|TRSS-Yun | [10:53:39.977][INFO][TRSSYz] - 正在加载 微信 适配器插件
0|TRSS-Yun | [10:53:40.011][INFO][TRSSYz] ----ヾ(￣▽￣)Bye~Bye~----
0|TRSS-Yun | [10:53:40.012][INFO][TRSSYz] 椰奶插件1.4.7初始化~
0|TRSS-Yun | [10:53:40.013][INFO][TRSSYz] -------------------------
0|TRSS-Yun | [10:53:40.106][INFO][TRSSYz] - 微信 适配器插件 加载完成
0|TRSS-Yun | [10:53:40.288][INFO][TRSSYz] - ICQQ 适配器插件 加载完成
0|TRSS-Yun | load Uid Data Done...
0|TRSS-Yun | [10:53:40.407][INFO][TRSSYz] - 正在加载 米游社小组件 插件
0|TRSS-Yun | [10:53:40.413][INFO][TRSSYz] ---------^_^---------
0|TRSS-Yun | [10:53:40.414][INFO][TRSSYz] 喵喵插件2.5.11初始化~
0|TRSS-Yun | [10:53:40.427][INFO][TRSSYz] - 米游社小组件插件 加载完成
0|TRSS-Yun | [10:53:40.436][INFO][TRSSYz] ---------^_^---------
0|TRSS-Yun | [10:53:40.437][INFO][TRSSYz] 图鉴插件1.2.9初始化~
0|TRSS-Yun | [10:53:41.492][INFO][TRSSYz] ------------QAQ------------
0|TRSS-Yun | [10:53:41.493][INFO][TRSSYz] liangshi伤害计算加载成功
0|TRSS-Yun | [10:53:41.494][INFO][TRSSYz] 如有计算错误可通过以下方式反馈
0|TRSS-Yun | [10:53:41.495][INFO][TRSSYz] 交流群反馈：807622774
0|TRSS-Yun | [10:53:41.495][INFO][TRSSYz] ---------------------------
0|TRSS-Yun | [10:53:41.519][MARK][TRSSYz] [liangshi]预设面板自动刷新完成
0|TRSS-Yun | [10:53:41.524][INFO][Plugin] 加载定时任务[2个]
0|TRSS-Yun | [10:53:41.525][INFO][Plugin] 加载插件[85个]
0|TRSS-Yun | [10:53:41.527][INFO][Listener] -----------
0|TRSS-Yun | [10:53:41.528][INFO][Listener] 加载监听事件中...
0|TRSS-Yun | [10:53:41.537][INFO][Listener] 加载监听事件[5个]
0|TRSS-Yun | [10:53:41.540][INFO][Adapter] -----------
0|TRSS-Yun | [10:53:41.541][INFO][Adapter] 加载适配器中...
0|TRSS-Yun | [10:53:41.551][MARK]----------
0|TRSS-Yun | [10:53:41.552][MARK]Package Version: icqq@0.6.10 (Released on 2024/2/4)
0|TRSS-Yun | [10:53:41.553][MARK]View Changelogs：https://github.com/icqqjs/icqq/releases
0|TRSS-Yun | [10:53:41.553][MARK]----------
0|TRSS-Yun | [10:53:41.747][INFO][] []获取到签名Api协议版本：9.0.70
0|TRSS-Yun | [10:53:41.748][INFO][] []使用协议：aPad_9.0.70.17645
0|TRSS-Yun | [10:53:41.902][MARK][] 183.47.99.24:8080 connected
0|TRSS-Yun | [10:53:41.983][MARK][] Welcome, 珊瑚宫心海 ! 正在加载资源...
0|TRSS-Yun | [10:53:42.154][MARK][] 加载了74个好友，3个群，0个频道，10个陌生人
0|TRSS-Yun | [10:53:42.157][MARK][] ICQQ(QQ) v0.6.10 已连接
0|TRSS-Yun | [10:53:42.159][INFO][Adapter] 加载适配器[7个]
0|TRSS-Yun | [10:53:42.160][INFO][WebSocket] 连接地址：ws://localhost:2536/[ComWeChat,GSUIDCore,OPQBot,OneBotv11,go-cqhttp]
0|TRSS-Yun | [10:53:42.162][MARK][TRSSYz] ----^_^----
0|TRSS-Yun | [10:53:42.364][INFO][] succeed to send: [Private()] [回复]重启成功，用时5.417秒
0|TRSS-Yun | [10:53:45.003][INFO][] recv from: [Private: (friend)] #状态
0|TRSS-Yun | [10:53:45.142][INFO][][#状态][状态统计(status)][开始处理]
0|TRSS-Yun | [10:53:45.551][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yun | [10:53:45.554][MARK][][#状态][状态统计(status)][完成0.410秒]

PM2      | [PM2][WORKER] Reset the restart delay, as app TRSS-Yunzai has been up for more than 30000ms
0|TRSS-Yunzai  | [10:56:14.051][INFO][] recv from: [Private: (friend)] #椰奶设置
0|TRSS-Yunzai  | [10:56:14.081][INFO][][#椰奶设置][椰奶配置(Settings)][开始处理]
0|TRSS-Yunzai  | [10:56:14.101][INFO][TRSSYz] puppeteer Chromium 启动中...
0|TRSS-Yunzai  | [10:56:14.104][MARK][][#椰奶设置][椰奶配置(Settings)][完成0.020秒]
0|TRSS-Yunzai  | [10:56:14.587][INFO][TRSSYz] puppeteer Chromium 启动成功 ws://127.0.0.1:44029/devtools/browser/0b2b417e-76b1-4e25-99a6-adc0a85ce8ac
0|TRSS-Yunzai  | [10:56:17.449][MARK][TRSSYz] [图片生成][yenai-plugin/admin/index][1次] 1165.86KB 2835ms
0|TRSS-Yunzai  | [10:56:18.045][INFO][] succeed to send: [Private()] [图片]
0|TRSS-Yunzai  | [10:56:44.347][INFO][] recv from: [Private: (friend)] #椰奶状态
0|TRSS-Yunzai  | [10:56:44.369][INFO][][#椰奶状态][椰奶状态(state)][开始处理]
0|TRSS-Yunzai  | [10:56:46.854][INFO][TRSSYz] [Yenai-Plugin][状态]背景图片请求成功 219.70KB 2469ms
0|TRSS-Yunzai  | [10:56:57.759][MARK][TRSSYz] [图片生成][yenai-plugin/state/index][2次] 829.67KB 4507ms
0|TRSS-Yunzai  | [10:56:58.779][INFO][] succeed to send: [Private()] [图片]
0|TRSS-Yunzai  | [10:56:58.780][MARK][][#椰奶状态][椰奶状态(state)][完成14.407秒]
0|TRSS-Yunzai  | [10:57:04.741][INFO][] recv from: [Private: (friend)] #状态
0|TRSS-Yunzai  | [10:57:04.757][INFO][][#状态][状态统计(status)][开始处理]
0|TRSS-Yunzai  | [10:57:05.326][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yunzai  | [10:57:05.327][MARK][][#状态][状态统计(status)][完成0.568秒]
0|TRSS-Yunzai  | [11:00:00.042][MARK][读取定时任务(0 0 * * * ?)][开始处理]
0|TRSS-Yunzai  | [11:00:00.054][MARK][读取定时任务(0 0 * * * ?)][完成0.012秒]
0|TRSS-Yunzai  | [11:03:04.112][INFO][] recv from: [Private: (friend)] #椰奶状态pro
0|TRSS-Yunzai  | [11:03:04.117][INFO][][#椰奶状态pro][椰奶状态(state)][开始处理]
0|TRSS-Yunzai  | [11:03:04.208][ERRO][TRSSYz] [Yenai-Plugin][状态]请求 Google(proxy) 过程中发生错误: request to https://google.com/ failed, reason: connect ECONNREFUSED 127.0.0.1:7890
0|TRSS-Yunzai  | [11:03:09.124][WARN][TRSSYz] [Yenai-Plugin][状态]请求 Google 超时
0|TRSS-Yunzai  | [11:03:09.129][WARN][TRSSYz] [Yenai-Plugin][状态]背景图请求失败，使用默认背景图 “../../../../../plugins/yenai-plugin/resources/state/img/bg/1.jpg” ，错误原因: GET Error，The operation was aborted.
0|TRSS-Yunzai  | [11:03:11.174][MARK][TRSSYz] [图片生成][yenai-plugin/state/index][3次] 852.50KB 2022ms
0|TRSS-Yunzai  | [11:03:12.015][INFO][] succeed to send: [Private()] [图片]
0|TRSS-Yunzai  | [11:03:12.016][MARK][][#椰奶状态pro][椰奶状态(state)][完成7.897秒]
0|TRSS-Yunzai  | [11:03:19.461][INFO][] recv from: [Private: (friend)] #状态pro
0|TRSS-Yunzai  | [11:03:19.471][INFO][][#状态pro][状态统计(status)][开始处理]
0|TRSS-Yunzai  | [11:03:20.049][INFO][] succeed to send: [Private()] [json消息]
0|TRSS-Yunzai  | [11:03:20.055][MARK][][#状态pro][状态统计(status)][完成0.581秒]

### 复现频率

经常出现

### Yenai-Plugin是否为当前最新版本？

- [X] 我最近已使用过`#椰奶更新`命令进行更新至最新版本

**Comment by Denfenglai** [comment]
TRSS-Yunzai近期修改了本体状态的优先级为负无限导致了此问题的发生，同时影响的还有猫猫状态、土块状态等，请向TRSS-Yunzai作者时雨星空反馈此问题。

**Comment by Denfenglai** [comment]
截止目前，时雨星空已在提交[f269007](https://github.com/TimeRainStarSky/Yunzai/commit/f26900756a8950333fb69dbb169a4dbd8b0d7191)中修复此问题，请更新TRSS-Yunzai以解决此问题！
