### ISSUE TITLE
[bug]：ntqq无法搜图

### ISSUE THREAD

**Issue by Mei-Sakura** [yeyang52/yenai-plugin#128]
### 这个问题是否已经存在？

- [X] 我已经搜索过[现有的问题](https://gitee.com/yeyang52/yenai-plugin/issues)并未发现相同问题

### Yunzai版本

Miao-Yunzai

### Node.js版本

v20.17.0

### 协议端名称

ICQQ

### 操作系统

Windows 11

### 复现步骤

使用ntqq无法正常识图，旧版qq正常

ntqq：
![CQ3)93_7I2@V0QE@`4{AI~C](https://github.com/user-attachments/assets/bf50396e-4fec-4c0f-a22f-93885137cda6)

旧版：
![image](https://github.com/user-attachments/assets/853c59d1-030a-48d0-9813-64454d2d58f8)

### 实际行为

应该是ntqq更换了新的图片url导致无法正常获取图片，通过napcatqq查看新版ntqq发送图片url为类似
https://multimedia.nt.qq.com.cn/download?appid=1406&amp;fileid=Cgk2MzI2NzA3MzMSFITKtT6CRLj9Wu-IcQixBaORdpYfGKS6BSD-CijWsvSurraIA1CAuy8&amp;spec=0&amp;rkey=CAESKBkcro_MGujoM0TxSI6EqUKGCaS3O5rIUDCM2ZUyzzgcLhe22l9DeTk,file_size=89380

### 复现频率

每次出现

### Yenai-Plugin是否为当前最新版本？

- [X] 我最近已使用过`#椰奶更新`命令进行更新至最新版本

**Comment by Denfenglai** [comment]
新版NT图床链接问题
TRSS-Yunzai直接 #更新ICQQ
Miao-Yunzai在崽根目录执行这个安装命令 然后重启
```sh
curl -# https://img.kookapp.cn/attachments/2024-09/11/66e0f2f7c93f4 -o node_modules/icqq/lib/message/parser.js
```
