### ISSUE TITLE
[bug]：`#清理xx没发言的人`出错

### ISSUE THREAD

**Issue by Jin1c-3** [yeyang52/yenai-plugin#132]
### 这个问题是否已经存在？

- [X] 我已经搜索过[现有的问题](https://gitee.com/yeyang52/yenai-plugin/issues)并未发现相同问题

### Yunzai版本

TRSS-Yunzai

### Node.js版本

18.20.4

### 协议端名称

LLOneBot

### 操作系统

Windows server

### 复现步骤

1. `#清理xx没发言的人`
2. 返回的res为：`错误：[{"ec":4,"errcode":0,"em":"no login [errcode:4:0]"}]`

### 预期行为

应该能正常删人

### 实际行为

实际为报错

### 错误日志或截图

![图片](https://github.com/user-attachments/assets/4e765c86-5677-404f-a390-91b93ba4f773)

### 其他说明

是否可以用`#踢人`的接口？

### 复现频率

每次出现

### Yenai-Plugin是否为当前最新版本？

- [X] 我最近已使用过`#椰奶更新`命令进行更新至最新版本

**Comment by yeyang52** [comment]
该协议端应该无法获取ck，故无法使用批量踢人接口，如使用**#踢人**接口批量踢人可能会有风控，只能设置间隔，效率太低，后续会将该接口设为备用接口，但无法保证效率

**Comment by yeyang52** [comment]
> 该协议端应该无法获取ck，故无法使用批量踢人接口，如使用**#踢人**接口批量踢人可能会有风控，只能设置间隔，效率太低，后续会将该接口设为备用接口，但无法保证效率

@Denfenglai 交给你了
