### ISSUE TITLE
[bug]：Ascii2D搜图没有图片（？）

### ISSUE THREAD

**Issue by Qyyxzz** [yeyang52/yenai-plugin#135]
### 这个问题是否已经存在？

- [X] 我已经搜索过[现有的问题](https://gitee.com/yeyang52/yenai-plugin/issues)并未发现相同问题

### Yunzai版本

trss-Yunzai

### Node.js版本

22.9.0

### 协议端名称

ncqq

### 操作系统

win11

### 复现步骤

#ac搜图或搜图

### 预期行为

输出内容图片

### 实际行为

未输出图片

### 错误日志或截图

![image](https://github.com/user-attachments/assets/7c3ddb85-cbad-41dc-af01-46de5fad39eb)
![e3fcbfbe1729fbcc736cb431096d584a](https://github.com/user-attachments/assets/bc6dbd21-a40e-4690-8e02-480d3f0af6cf)
![16a77de9b8a04699465e928129d676e3](https://github.com/user-attachments/assets/0e26be02-b97b-4ab7-b9dd-d5af7d255260)

### 复现频率

每次出现

### Yenai-Plugin是否为当前最新版本？

- [X] 我最近已使用过`#椰奶更新`命令进行更新至最新版本

**Comment by yeyang52** [comment]
我看你的输出日志没有问题，是否有协议端的日志

**Comment by yeyang52** [comment]
> > 我看你的输出日志没有问题，是否有协议端的日志
> 
> 对了 还有状态的上下行网速图是得有接线才有吗 我的没有

扔张椰奶状态来
