### ISSUE TITLE
[bug]：昵称：undefined 

### ISSUE THREAD

**Issue by A1Panda** [yeyang52/yenai-plugin#136]
### 这个问题是否已经存在？

- [X] 我已经搜索过[现有的问题](https://gitee.com/yeyang52/yenai-plugin/issues)并未发现相同问题

### Yunzai版本

TRSS-Yunzai V3.1.3

### Node.js版本

23.1.0

### 协议端名称

Napcat

### 操作系统

Arch Linux

### 复现步骤

加群申请昵称提示undefined 

### 预期行为

正常获取到用户昵称

### 实际行为

![image](https://github.com/user-attachments/assets/732d5e28-c054-429f-938c-5d8ff34f8db3)

### 错误日志或截图

![image](https://github.com/user-attachments/assets/187c4c03-d927-4cbc-99a8-b019a5aafd16)
![image](https://github.com/user-attachments/assets/e81b695d-2436-4408-b417-7ca7f497db1f)

### 复现频率

每次出现

### Yenai-Plugin是否为当前最新版本？

- [X] 我最近已使用过`#椰奶更新`命令进行更新至最新版本

**Comment by Xbaishu** [comment]
使用napcat 链接onebotv11协议，目前最新版椰奶插件依然无法读取，喵崽或者trss崽皆不能读取QQ用户昵称

日志如下
[22:55:42.592][INFO][1355204*** <= 1056676***, 1425890***] 加群请求：add (175319613686****)
[22:55:42.650][INFO][1355204*** => 1056676004] 发送群消息：[{"type":"text","data":{"text":"有一个加群通知，管理员快去看看吧~\n"}},{"type":"image","data":{"file":"https://q1.qlogo.cn/g?b=qq&s=100&nk=142589****"}},{"type":"text","data":{"text":"QQ号：142589****\n"}},{"type
":"text","data":{"text":"昵称：undefined\n"}},{"type":"text","data":{"text":""}}]
[22:55:44.005][INFO][  TRSSYz  ] [Yenai-Plugin]加群申请
[22:55:44.007][INFO][1355204*** => 1287030***] 发送好友消息：[{"type":"image","data":{"file":"https://p.qlogo.cn/gh/1056676***/1056676***/0"}},{"type":"text","data":{"text":"[通知(1355204***) - 加群申请]\n"}},{"type":"text","data":{"text":"群号：1056676***\n"}},{"type":"
text","data":{"text":"群名：****\n"}},{"type":"text","data":{"text":"账号：1425890***\n"}},{"type":"text","data":{"text":"昵称：undefined"}},{"type":"text","data":{"text":""}},{"type":"text","data":{"text":"\n"}}]

**Comment by A1Panda** [comment]
> 皆

去用我的Group插件

**Comment by DenFengLai** [comment]
> 使用napcat 链接onebotv11协议，目前最新版椰奶插件依然无法读取，喵崽或者trss崽皆不能读取QQ用户昵称
> 
> 日志如下 [22：55：42.592][INFO][1355204*** <= 1056676***， 1425890***] 加群请求：add （175319613686****） [22：55：42.650][INFO][1355204*** => 1056676004] 发送群消息：[{“type”：“text”，“data”：{“text”：“有一个加群通知，管理员快去看看吧~\n”}}，{“type”：“image”，“data”：{“file”：“https://q1.qlogo.cn/g?b=qq&s=100&nk=142589****”}}，{“type”：“text”，“data”：{“text”：“QQ号：142589****\n”}}，{“type ”：“text”，“data”：{“text”：“昵称：undefined\n”}}，{“type”：“text”，“data”：{“text”：“”}}] [22：55：44.005][INFO][ TRSSYz ] [Yenai-Plugin]加群申请 [22：55：44.007][INFO][1355204*** => 1287030***] 发送好友消息：[{“type”：“image”，“data”：{“file”：“https：//p.qlogo.cn/gh/1056676***/1056676***/0”}}，{“type”：“text”，“data”：{“text”：“[通知（1355204***） - 加群申请]\n”}}，{“type”：“text”，“data”：{“text”：“群号：1056676***\n”}}，{“type”：“ text”，“data”：{“text”：“群名：*_**\n”}}，{“type”：“text”，“data”：{“text”：“账号：1425890**_\n“}}，{”type“：”text“，”data“：{”text“：”昵称：undefined“}}，{”type“：”text“，”data“：{”text“：”“}}，{”type“：”text“，”data“：{”text“：”\n“}}]

您的问题我已知晓，我想表示的是，此类数据均由框架和协议提供，椰奶插件只是加以调用，您应当对您的框架或协议提出issue而并非椰奶插件，因为此功能在其他协议上正常使用
