### ISSUE TITLE
[功能建议]: 找不到对应版本的依赖

### ISSUE THREAD

**Issue by A1Panda** [yeyang52/yenai-plugin#137]
### 问题描述

找不到需要的依赖

### 实现方式

pnpm i

### 其他说明

![image](https://github.com/user-attachments/assets/3079757e-dcc5-4c04-b9c9-6251e9dd9c43)

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献到本插件

**Comment by yeyang52** [comment]
这是一个开发依赖请无视他
