### ISSUE TITLE
[FEATURE] Ignore `/config/config` directory, use something like `/config/default_config`

### ISSUE THREAD

**Issue by FUTURETECH6** [yeyang52/yenai-plugin#15]
Changes to `/config/config` will prevent repo from updating, a merge is needed.

Possible solution: configs can be stored in another directory (i.e., `/config/default_config`), and create `/config/config` when it's not found during bot execution.

**Comment by yeyang52** [comment]
That's what I did.

**Comment by FUTURETECH6** [comment]
Sorry I didn't check the commit history 74f66003c5b41f690ac83a2030e7bf103a5f90d3 about this
