### ISSUE TITLE
fun.js中的一些修改

### ISSUE THREAD

**Issue by Reol077** [yeyang52/yenai-plugin#18]
原来的写法使用起来有bug
修改后为：

    let url = picObj.url || picObj

    // 数组随机取或指定
    if (Array.isArray(url)) url = _.sample(url)

    url = encodeURI(url)

还有我自己找的一些接口有的返回的是字符串形式的json
加了一个判断

    if (typeof (res) == 'str') res = JSON.parse(res)

**Comment by yeyang52** [comment]
？不是给了返回json的示例吗

**Comment by Reol077** [comment]
我的意思是，返回的是一个json形式的字符串，要转化一下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: "ζั͡ޓއއއ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyang52/yenai-plugin] fun.js中的一些修改 (Issue #18)





 
？不是给了返回json的示例吗

**Comment by yeyang52** [comment]
你用json就会自动转换

**Comment by Reol077** [comment]
噢噢好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 晚上9:09
收件人: ***@***.***&gt;; 
抄送: "ζั͡ޓއއއ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyang52/yenai-plugin] fun.js中的一些修改 (Issue #18)





 
你用json就会自动转换

**Comment by yeyang52** [comment]
请参考[这一行代码](https://github.com/yeyang52/yenai-plugin/blob/949b987e5b712675574cb7933ef97d6611a3466d/apps/fun.js#L343)

**Comment by Reol077** [comment]
抱歉抱歉，没太注意看，想着判断一下就好了
