### ISSUE TITLE
#搜图报错 ┭┮﹏┭┮

### ISSUE THREAD

**Issue by RemYui** [yeyang52/yenai-plugin#19]
![QQ图片20230215211100](https://user-images.githubusercontent.com/72900249/219036683-537837ba-54c3-4ee4-9301-207d10956fbf.jpg)

**Comment by yeyang52** [comment]
请根据[常见问题](https://github.com/yeyang52/yenai-plugin/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#ascii2d)解决

**Comment by RemYui** [comment]
好的，谢谢佬
