### ISSUE TITLE
建议增加消息批量发送

### ISSUE THREAD

**Issue by lin-junliang** [yeyang52/yenai-plugin#2]
目前给好友发消息的格式是“发好友 10000 消息”，希望可以添加回车或其他任意格式，在一条信息里给多个好友发送消息
例如：
发好友 10000 消息
发好友 10001 消息
发好友 10002 消息
发好友 10003 消息
发好友 10004 消息

这么做的目的是为了快速发通知，目前的想法是通知米游社签到失败，分多次发送的话会有点麻烦

**Comment by yeyang52** [comment]
群发非常容易封号所以不会考虑添加群发

**Comment by lin-junliang** [comment]
可以延时几秒 @yeyang52
