### ISSUE TITLE
椰奶状态

### ISSUE THREAD

**Issue by TiantongAlice** [yeyang52/yenai-plugin#21]
椰奶状态CPU占用不显示

**Comment by TiantongAlice** [comment]
![468ebf9d78d4ee94](https://user-images.githubusercontent.com/126250887/226174444-f45ced76-c4ae-4fe6-b909-45476d52d18f.jpg)

**Comment by yeyang52** [comment]
手机需要root权限

**Comment by TiantongAlice** [comment]
谢谢大佬，问题已解决
