### ISSUE TITLE
P站模块设置问题

### ISSUE THREAD

**Issue by Crazypeak** [yeyang52/yenai-plugin#22]
设置好refresh_token后重启仍然无法检测到登录状态，model里是初始化的时候进行登录，但日志冇显示登录失败。初步怀疑是冇检测到配置文件的值并进行登录

**Comment by Crazypeak** [comment]
1、设置好refresh_token后重启仍然无法检测到登录状态，model里是初始化的时候进行登录，但日志冇显示登录失败。初步怀疑是冇检测到配置文件的值并进行登录
2、设置代理问题，用的是clash代理，走socks模式，正常curl能访问google，但p站模块设置代理后连不上代理
           ----Request Post Error，reason： connect ECONNREFUSED 127.0.0.1:7890

**Comment by yeyang52** [comment]
你确定你的网络可以访问到Pixiv吗
