### ISSUE TITLE
saucenao搜图有bug

### ISSUE THREAD

**Issue by oio10** [yeyang52/yenai-plugin#30]
![33b0f64095b1e72.png](https://user-images.githubusercontent.com/100659265/228711560-5092c7eb-dd86-4017-a0a1-95b961bd887b.png)![IMG_20230330_102035.jpg](https://user-images.githubusercontent.com/100659265/228711574-8eb531d0-5bf8-481a-a37a-ab7a6106740d.jpg)
如图

**Comment by yeyang52** [comment]
我还没遇到，可以让问题复现吗
