### ISSUE TITLE
群管功能

### ISSUE THREAD

**Issue by wanci67** [yeyang52/yenai-plugin#31]
#清理n天没发言的人，功能报错{"ec":3,"errcode":0,"em":" [errcode:3:0]"}

**Comment by yeyang52** [comment]
说的是踢多少人

**Comment by wanci67** [comment]
![Screenshot_2023-04-02-00-26-29-509_com tencent mobileqq](https://user-images.githubusercontent.com/129612825/229302811-901dfe8d-59d2-42a7-8732-24924e43d4f2.png)
这样也算正常吗？

**Comment by wanci67** [comment]
> 说的是踢多少人

![Screenshot_2023-04-02-00-26-29-509_com tencent mobileqq](https://user-images.githubusercontent.com/129612825/229302856-0352c161-79ff-47b1-b33c-c8a8897f55fe.png)

这样也是正常吗？
