### ISSUE TITLE
proxy代理问题

### ISSUE THREAD

**Issue by CICILC** [yeyang52/yenai-plugin#32]
报错
![image](https://user-images.githubusercontent.com/115946224/230103859-f0ffd125-df6a-41f3-a226-3baa25a8f73a.png)
配置文件：http端口9080
![image](https://user-images.githubusercontent.com/115946224/230104084-228bcd0a-f332-4b15-9ea8-42fb7eba5361.png)
代理软件日志：
![image](https://user-images.githubusercontent.com/115946224/230104221-6e8c8d15-c303-496d-bf5d-c4b3f8180dab.png)
根据代理软件日志来看应该是已经转发了流量了 不知道问题出在哪了
感谢大佬

**Comment by yeyang52** [comment]
查看你的代理软件的代理服务器有问题吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月5日(周三) 晚上10:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeyang52/yenai-plugin] proxy代理问题 (Issue #32)




 
报错
 
 配置文件：http端口9080
 
 代理软件日志：
 
 根据代理软件日志来看应该是已经转发了流量了 不知道问题出在哪了
 感谢大佬

**Comment by CICILC** [comment]
我再试试

**Comment by CICILC** [comment]
应该是代理问题
