### ISSUE TITLE
雷神收益曲线会发送2次的问题

### ISSUE THREAD

**Issue by lin-junliang** [yeyang52/yenai-plugin#33]
![image](https://user-images.githubusercontent.com/59049320/230276082-a8720afe-5a52-46c2-b88d-a86801166d33.png)
![image](https://user-images.githubusercontent.com/59049320/230276103-66ca42c4-fc84-42e6-bef5-8f45065f519f.png)

雷神收益曲线会发送2次的问题，暂时未发现其他角色有该问题

**Comment by yeyang52** [comment]
有没有一种可能我是说可能两张图是不一样的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 中午1:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeyang52/yenai-plugin] 雷神收益曲线会发送2次的问题 (Issue #33)




 

 
 
雷神收益曲线会发送2次的问题，暂时未发现其他角色有该问题
