### ISSUE TITLE
大佬，作为一款群管助手，怎么能没有自动撤回群成员违规词的功能呢

### ISSUE THREAD

**Issue by yinheshiji** [yeyang52/yenai-plugin#34]
**问题描述**
请简要描述您想要的新功能。

**实现方式**
请简要描述您希望实现这个新功能的方式。

**当前的问题**
如果没有这个新功能，您当前面临的问题是什么？

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by yinheshiji** [comment]
大佬效率这么高？赞！！！辛苦了，小小捐赠不成敬意，祝您保重身体越来越好！

**Comment by yeyang52** [comment]
#新增违禁词（模糊|精确）（踢|禁|撤|踢撤|禁撤）.*

**Comment by yinheshiji** [comment]
早些休息，慢慢来。我也熬夜了...目前指令还不能触发，不过总体框架没问题^.^

**Comment by yeyang52** [comment]
请自行查看[文档](https://www.yenai.ren/features/GroupAdmin.html#%E6%96%B0%E5%A2%9E%E8%BF%9D%E7%A6%81%E8%AF%8D)

**Comment by yinheshiji** [comment]
好的，建议增加2项违禁词指令

**Comment by yeyang52** [comment]
撤回并禁言已经有了，请阅读文档
