### ISSUE TITLE
Ascii2D搜索失败

### ISSUE THREAD

**Issue by HugeByte** [yeyang52/yenai-plugin#36]
**问题描述**
调用Ascii2D搜索会失败并报错，根据后台日志信息，疑似触发Cloudflare盾导致搜索失败

**如何复现**
使用#ac搜图后发送任意图片进行搜索

**期望结果**
能绕过盾最好，若难度太高的话，希望能增加结果提示语，如遇到风控，搜索超时之类的

**实际结果**
报错Ascii2D搜索失败，错误原因：
无错误原因提示

**截图**
![2](https://user-images.githubusercontent.com/40591485/230718186-294a8459-4fd3-4fe7-ba44-47d729d94802.png)
![1](https://user-images.githubusercontent.com/40591485/230718190-498b8115-3b90-4ed5-bd34-c44fc8c31aef.png)

**其他说明**
尝试更换节点，重启服务器，等待几天后重试等操作均无法绕过Cloudflare盾

**Comment by yeyang52** [comment]
是否使用代理，是否开启Puppeteer 请求 ascii2d

**Comment by HugeByte** [comment]
之前一直使用代理反代了ascii2d.net与cloudflare.com，频繁触发cf盾后试过关闭代理，无法绕过
目前已在config中配置ascii2dUsePuppeteer为true，并分别尝试使用TLSv1.1与TLSv1.2版本，仍无法成功绕过cf盾
![1](https://user-images.githubusercontent.com/40591485/230731993-d0b0a7fc-01bc-4e1d-ad19-d74defe3f833.png)

**Comment by yeyang52** [comment]
请更新到最新版安装依赖后使用Puppeteer 请求 ascii2d

**Comment by HugeByte** [comment]
已更新，目前ascii2d恢复正常
顺便捉个小虫，缺失依赖提示语中pnpm add puppeteer-extr少了一个a
![1](https://user-images.githubusercontent.com/40591485/230733929-822d4f6a-c5f2-4c40-b987-8386121cf6ca.png)
