### ISSUE TITLE
请求椰奶状态时，一直提示没有检测到systeminformation依赖

### ISSUE THREAD

**Issue by syp1999** [yeyang52/yenai-plugin#38]
**问题描述**
请求椰奶状态时，一直提示没有检测到systeminformation依赖。
此前一直是可用的，自从我手动git pull到最新代码后，就一直是这样了。
已经尝试运行过pnpm add systeminformation -w了，依旧无效。

**如何复现**
没有找到明确步骤

**期望结果**
椰奶状态能正常使用

Yunzai-Bot根目录的package.json文件里也可以看到有所需要的依赖包
![image](https://user-images.githubusercontent.com/46620920/231536837-48a187f6-db2d-4c5f-8d4b-f6b603f1ff91.png)

**Comment by yeyang52** [comment]
在yenai-plugin执行`pnpm i`试试

**Comment by syp1999** [comment]
> 在yenai-plugin执行`pnpm i`试试

感谢回复，但尝试过了，还是不行……

**Comment by yeyang52** [comment]
可以尝试更换包管理器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月17日(周一) 凌晨1:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yeyang52/yenai-plugin] 请求椰奶状态时，一直提示没有检测到systeminformation依赖 (Issue #38)




  
在yenai-plugin执行pnpm i试试
  
感谢回复，但尝试过了，还是不行……

**Comment by syp1999** [comment]
> 可以尝试更换包管理器
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月17日(周一) 凌晨1:12 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yeyang52/yenai-plugin] 请求椰奶状态时，一直提示没有检测到systeminformation依赖 (Issue #38) 在yenai-plugin执行pnpm i试试 感谢回复，但尝试过了，还是不行…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;


找到原因了，pnpm add systeminformation -w命令安装的包为默认最新目前是5.17.9的版本。
此版本的包是个空包，通过node_modules可查到安装完毕后目录里只有文件夹结构，没有任何文件。
导致导包出错！

在通过`pnpm add systeminformation@5.17.1 -w`命令安装您默认package.json里目标版本5.17.1的包之后就一切正常了。

问题已解决！！
