### ISSUE TITLE
ASCII2d搜图报错

### ISSUE THREAD

**Issue by Fhm-newbie** [yeyang52/yenai-plugin#40]
**问题描述**
请简要描述您遇到的问题。
ASCII2d搜图报错，回复如图
![Screenshot_20230415_134327_com tencent mobileqq](https://user-images.githubusercontent.com/63446200/232186859-c1bf5fdd-ce83-4ba7-a4b0-6823e34d8b10.jpg)
日志如图
![5c8a126e89effd8d](https://user-images.githubusercontent.com/63446200/232186879-a81e408a-6b45-44e8-9b23-bcb33934d63f.jpg)

**如何复现**
请详细描述如何复现问题，步骤越详细越好。
1.根据文档安装插件和依赖
2.#搜图
3.发送图片
4.报错

**Comment by yeyang52** [comment]
https://www.yenai.ren/faq.html#openssl-%E9%94%99%E8%AF%AF

**Comment by Fhm-newbie** [comment]
常见问题看到了，打扰了
