### ISSUE TITLE
插件运行过程中调用大量 powershell 占用 cpu

### ISSUE THREAD

**Issue by Hochfart0** [yeyang52/yenai-plugin#41]
**问题描述**
请简要描述您遇到的问题。

bot运行过程中突然 cpu 占用大幅增加，查看任务管理器发现有很多 powershell 运行，重启 bot 无效；逐个插件排查发现 加载该插件会出现这个问题。
![image](https://user-images.githubusercontent.com/38368552/232226945-71ba7075-0489-4549-9e09-d52b9907b048.png)

**如何复现**
请详细描述如何复现问题，步骤越详细越好。

不明，运行一段时间后会出现，重启电脑后再启动 bot 刚开始会出现一些 powershell 任务 1s 左右会消失，运行一段时间后会出现该问题

**期望结果**
请简要描述您期望得到的结果。

**实际结果**
请简要描述您实际得到的结果。

**截图**
如果可以，请提供相关截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/38368552/232226750-cd2ef86e-a814-412b-b6c8-1931e74be717.png)

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by Hochfart0** [comment]
系统 win10 1903

**Comment by yeyang52** [comment]
请使用`#椰奶设置状态任务关闭`

**Comment by Hochfart0** [comment]
关闭设置后，重启 bot 还是会出现多个 PS 任务；
关机重启后首次运行 bot 短时间内正常，但是 pnpm restart 后又出现了😢
![image](https://user-images.githubusercontent.com/38368552/232265159-7c6d06e9-4902-4682-8797-ce3b5f9ca36e.png)
![image](https://user-images.githubusercontent.com/38368552/232265167-bf5b3636-37ea-4fa3-b185-f12fd83ffe47.png)

**Comment by Hochfart0** [comment]
新情况，PS 任务出现了5分钟后都消失了，很怪，我先观察下再反馈
