### ISSUE TITLE
#群发言榜单 、#谁是龙王，等命令报错

### ISSUE THREAD

**Issue by liujhs** [yeyang52/yenai-plugin#42]
**问题描述**
发送#群发言榜单 、#谁是龙王命令报错

**如何复现**
在群里发送#群发言榜单 、#谁是龙王命令

**期望结果**
机器人发送榜单

**实际结果**
无响应，后台报错

**截图**
![image](https://user-images.githubusercontent.com/89055271/232655778-49b22020-7d1e-4226-9c06-bb46c15463be.png)

**Comment by yeyang52** [comment]
你的云崽版本号是多少？

**Comment by liujhs** [comment]
> 你的云崽版本号是多少？

v3.0，上周还能用，今天发现报错了

**Comment by yeyang52** [comment]
乐鸟版本的？

**Comment by liujhs** [comment]
> 乐鸟版本的？

是的，是这个版本有问题吗

**Comment by liujhs** [comment]
> 乐鸟版本的？

换版本可以用了
