### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by subreast** [yeyang52/yenai-plugin#44]
**问题1**
![image](https://user-images.githubusercontent.com/132317906/236454264-864e765c-27ca-43f3-a0f9-a256dd205de2.png)
1.需要在云仔重新开机的时候发送
2. 第一个发送禁言或者解禁指令会回复找不到这个人

**问题2**
![image](https://user-images.githubusercontent.com/132317906/236455015-c07314e1-08fd-427a-a995-94bbb1941aae.png)
1.解除全部用户禁言无效

**Comment by yeyang52** [comment]
重新启动后没有对应群的缓存列表，获取一次就好了
