### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by subreast** [yeyang52/yenai-plugin#45]
**问题描述**
定时禁言任务取消不了，重启还是会有

![@U5F_CQAR9YK N3I25YCXZY](https://user-images.githubusercontent.com/132317906/236601038-e9999236-63a2-4adf-a99a-688bcf708b14.png)
![D4LUXYZ7OCR9PAEZ$NWL%LF](https://user-images.githubusercontent.com/132317906/236601042-8dae8482-8e23-40a3-b319-d153679bee9b.png)

**Comment by yeyang52** [comment]
你自己改了？椰奶哪有删除定时任务这个指令？

**Comment by subreast** [comment]
试了一下就那个群的定时任务取消不了，别的群可以，真奇怪
