### ISSUE TITLE
关于椰奶状态网速统计图有个问题想请教一下

### ISSUE THREAD

**Issue by waiwaiex** [yeyang52/yenai-plugin#46]
![QQ截图20230303115241](https://user-images.githubusercontent.com/66713455/236603585-b356e042-7cf1-4d85-8ed2-2b916511d062.jpg)
大佬，我js这块纯小白，调试也不咋会。有个问题想请教一下，如图，获取网速信息的时候，获取到的是虚拟网卡的信息，数据都是空的因此椰奶状态的网速统计也是空的。
我查了下systeminformation文档，文档给出的示例是networkStatus()内可以传参来获取指定网卡的信息（如图103行）。看打印结果也确实能获取到。
现在我该怎么改这个101行代码里的valueObject,才能使它调networkStatus方法的时候可以传个网卡名的参数进去啊。

**Comment by yeyang52** [comment]
你可以将valueObject更改为
```js
let valueObject = {
  networkStats: '(以太网),rx_sec,tx_sec,iface',
  currentLoad: 'currentLoad',
  mem: 'active',
  fsStats: 'wx_sec,rx_sec'
}
```
具体可参考[为si.get提供参数](https://systeminformation.io/general.html)

**Comment by waiwaiex** [comment]
谢谢大佬，文档没看仔细，眼瞎了
