### ISSUE TITLE
update更新bot无响应

### ISSUE THREAD

**Issue by Coolboost** [yeyang52/yenai-plugin#49]
在QQ聊天界面发送#椰奶更新后bot没有显示更新失败与否的消息，检查控制台发现git -C指令错误

![图片](https://github.com/yeyang52/yenai-plugin/assets/95410086/c9a88f01-2a1b-4432-97c6-eba682367a6e)
![图片](https://github.com/yeyang52/yenai-plugin/assets/95410086/560e5b9b-5246-44fa-8646-b949f30c90ad)

经检查发现yenai/plugin/apps/update.js中的更新函数指令有误
![图片](https://github.com/yeyang52/yenai-plugin/assets/95410086/8fce8c1a-02af-4e8f-a7a0-ae0a0ddbd0d8)

建议将update.js中所有的git -C改为git -c
![图片](https://github.com/yeyang52/yenai-plugin/assets/95410086/df0b618c-e343-4180-bc05-0d73ba0401c6)

**Comment by yeyang52** [comment]
`git -C`为指定路径而`git -c`用于在当前 Git 命令中设置一个临时配置选项
具体你可以参考官方文档
[-C \<path\>](https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt)
[-c \<name\>=\<value\>](https://git-scm.com/docs/git#Documentation/git.txt--cltnamegtltvaluegt)

**Comment by Coolboost** [comment]
> `git -C`为指定路径而`git -c`用于在当前 Git 命令中设置一个临时配置选项 具体你可以参考官方文档 [-C <path>](https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt) [-c <name>=<value>](https://git-scm.com/docs/git#Documentation/git.txt--cltnamegtltvaluegt)
> 
> 而出现你这个错误可能是你的git版本不支持`git -C`命令，请尝试将你的git版本升级至`v1.8.5`以上

了解了，确实是我版本过低
![图片](https://github.com/yeyang52/yenai-plugin/assets/95410086/5daef0fe-ccf7-46c7-bac4-183935872775)
