### ISSUE TITLE
关于群员触发违禁词后的建议，和解禁群员的处理结果的建议

### ISSUE THREAD

**Issue by yinheshiji** [yeyang52/yenai-plugin#51]
一些小建议
一、在群员触发违禁词后，显示的处理结果对违禁词进行强模糊处理，并在一定时间后自动撤回处理结果，以免造成二次宣传
二、解禁群成员后的处理结果，在一定时间后自动撤回
谢谢

**Comment by yeyang52** [comment]
强模糊处理？
