### ISSUE TITLE
群管功能：#改群头像    时，bot自身身份认识错误

### ISSUE THREAD

**Issue by wfqyys** [yeyang52/yenai-plugin#54]
**问题描述**
更新到最新版之后
改群头像的时候出现：明明他是群主却说没有管理员权限，导致改不了，
后台并没有报错

**如何复现**
重启，再试，再重启，再试

**期望结果**
请修复一下bug

**实际结果**
请简要描述您实际得到的结果。

**截图**
![$} 8%MHQ2$OW{P%@GPKF20I](https://github.com/yeyang52/yenai-plugin/assets/82580667/ca771864-1a8d-4d42-9f34-28a82d82b629)
![image](https://github.com/yeyang52/yenai-plugin/assets/82580667/2db00769-b5cb-413e-b53d-7fc3f9d79fa1)

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by yeyang52** [comment]
trss?
