### ISSUE TITLE
当机器人为群主时，一个管理员可以禁言另一个管理员

### ISSUE THREAD

**Issue by feixuei** [yeyang52/yenai-plugin#57]
**问题描述**
如题
当机器人为群主时，一个管理员可以禁言另一个管理员

**如何复现**
#禁言xxx

**期望结果**
一个管理员应不能禁言另一个管理员

**实际结果**
一个管理员可以禁言另一个管理员

**Comment by yeyang52** [comment]
在[这一段](https://github.com/yeyang52/yenai-plugin/blob/828c1b1e88dac349b0f34ffcde38b2fb586c39fe/model/GroupAdmin.js#L378)有进行判断管理不能禁言管理
