### ISSUE TITLE
用户白名单

### ISSUE THREAD

**Issue by xyyyds1234** [yeyang52/yenai-plugin#59]
**问题描述**
用户白名单，也就是用户加了白名单之后不会被禁言和不会被机器人踢出撤回等，尽量违禁词那个也加上，还有可以自由添加和删除白名单和白名单列表等

**实现方式**
其实用户白名单就跟主人一样的但是白名单权限较弱，实现功能方法有阻止功能发起指令跟功能白名单差不多但是功能白名单之后其他指令将无响应，也可以在获取用户文件是否有白名单然后自动更改功能黑名单在指令发起结束自动删除功能黑名单可以实现指令无法对别人响应，没有白名单则不会响应这个指令

**当前的问题**
如果没有这个功能可能会违禁词会误禁人，可能会被机器人误踢等，加了主人可能会面临别人乱用指令等，所以需要用户白名单，

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by Denfenglai** [comment]
已更新：https://github.com/yeyang52/yenai-plugin/commit/47dd2779022719fdc18f6d2f599852190a0bd8ae
