### ISSUE TITLE
Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant

### ISSUE THREAD

**Issue by tianyisama** [yeyang52/yenai-plugin#62]
云崽版本：喵崽3.1.0，环境Windows2012，node版本16.18.0，使用看看周榜此类功能会出现如下错误：

Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant

控制台并无详细信息，而是直接输出该错误
![image](https://github.com/yeyang52/yenai-plugin/assets/118712549/ae168883-6366-439b-ab04-14d4b01b4c31)
重装插件也不能解决问题

**Comment by 8852690** [comment]
你是否有绑定过pixiv的token？如果没有的话可能不被允许使用这个功能。。。
