### ISSUE TITLE
群聊无法使用椰奶tag

### ISSUE THREAD

**Issue by lava081** [yeyang52/yenai-plugin#67]
**问题描述**
群聊使用椰奶tag，发送完正在找setu之后没有后续消息，私聊使用此功能，主人和群员都正常。
群聊使用无内鬼功能，不附加张数时正常，附加张数(如“#无内鬼3张”)后没有任何响应。

**Yunzai版本**
Miao-Yunzai v3.1.0 & Yenai-Plugin 1.3.0

**如何复现**
请详细描述如何复现问题，步骤越详细越好。

1. 群聊发送“#椰奶tag5张七七”
2. 机器人回复“正在给你找setu了，你先等等再冲~”
3. 控制台报告[setuTag]命令处理完成，实际没有发送消息
4. 私聊发送“#椰奶tag5张七七”
5. 机器人按要求转发了5张图片
6. 群聊发送“#无内鬼3张”
7. 机器人回复“你先别急，正在找了~”
8. 控制台报告[setuRandom]命令处理完成，实际没有发送消息
9. 私聊发送“#无内鬼3张”
10. 机器人按要求转发了3张图片
11. 群聊发送“#无内鬼”
12. 机器人按要求转发了1张图片

**期望结果**
群聊和私聊结果一致

**实际结果**
群聊无响应

**截图**
![20230824_111232_831](https://github.com/yeyang52/yenai-plugin/assets/69086800/fd5e502d-d0b4-4a9c-bae4-8e509d9ab6f2)

**其他说明**

**Comment by yeyang52** [comment]
应该是api问题
