### ISSUE TITLE
可否让椰奶插件添加对WindowsTerminal终端的支持

### ISSUE THREAD

**Issue by FYSH2003** [yeyang52/yenai-plugin#68]
当我使用#椰奶状态pro时，总会提示如下内容：

 请检查是否使用git bash启动Yunzai-bot
错误信息：'bash' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

可以添加对WindowsTerminal终端的支持吗？git窗口在我的服务器上有时会卡死

**Comment by TimeRainStarSky** [comment]
https://www.jianshu.com/p/450aac19d981

**Comment by FYSH2003** [comment]
已解决，感谢！
