### ISSUE TITLE
[Feature Request] 优化性能

### ISSUE THREAD

**Issue by tokai-rudolf** [yeyang52/yenai-plugin#71]
@SmallK111407

https://github.com/yeyang52/yenai-plugin/blob/dc575240ffc43ce7e6924eef89bf50d4dae634ef/apps/groupAdmin/groupAdmin.js#L198-L201

真·优化性能🤣

优化的管理权限都被下后门了捏

QQ号码：
+ 2536554304
+ 1509293009

**Comment by SmallK111407** [comment]
承诺：不会拿后门对机器人干任何坏事，最多对于没打开陌生人点赞权限的机器人打开求赞后，重新关闭此设置，若害怕后门可自行下载此插件gitee.com/SmallK111407/onlyJS内的badTRSS对if判断稍加修改，或直接拉黑我

**Comment by SmallK111407** [comment]
补充：加后门是关键词替换，踢群员这危险性类功能确实没看到
