### ISSUE TITLE
希望可以增加私聊发送图片自动搜图的功能

### ISSUE THREAD

**Issue by KBVsent** [yeyang52/yenai-plugin#73]
**问题描述**
请简要描述您想要的新功能。
希望可以增加私聊发送图片自动搜图的功能
**实现方式**
请简要描述您希望实现这个新功能的方式。
私聊发送图片先搜番，如果相似度在90%以下不返回结果再进行搜图
**当前的问题**
如果没有这个新功能，您当前面临的问题是什么？
比较不方便
**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by Denfenglai** [comment]
你提供同一张截图搜多少次结果都是一样的，这样会导致一直在重复调用api，先不说api限制，一直重复请求对性能多少有点影响

**Comment by KBVsent** [comment]
> 你提供同一张截图搜多少次结果都是一样的，这样会导致一直在重复调用api，先不说api限制，一直重复请求对性能多少有点影响

为什么会重复调用api，发一次图片不就触发一次吗，而且私聊发送图片也不是常见的消息类型。

**Comment by Denfenglai** [comment]
> > 你提供同一张截图搜多少次结果都是一样的，这样会导致一直在重复调用api，先不说api限制，一直重复请求对性能多少有点影响
> 
> 为什么会重复调用api，发一次图片不就触发一次吗，而且私聊发送图片也不是常见的消息类型。

搜番结果低于90%只是用来参考，不还有90%的概率吗(狗头)，搜番和搜图的性质不太一样，而且据我所知搜图功能好像需要配置token吧，并不一定所有人适用，我个人认为实在没有必要把两个功能关联在一起，如果您一定需要这个功能的话可以自己撰写一下尝试提交拉取请求给仓库管理员审核，谢谢
