### ISSUE TITLE
代理配置未生效

### ISSUE THREAD

**Issue by AIxPha** [yeyang52/yenai-plugin#75]
**问题描述**

椰奶状态pro 超时生成失败
原因是登录了Discord但连不上
已配置椰奶配置文件里的 proxy.yaml
![image](https://github.com/yeyang52/yenai-plugin/assets/120633018/1fccbedf-255f-49f1-a16e-e3f2ba2a85b3)

**复现条件**

在登录设备有Discord适配器未全局代理系统的条件下使用 椰奶状态pro
![image](https://github.com/yeyang52/yenai-plugin/assets/120633018/67b904ad-116e-4b23-83cc-3132158bfd23)

**个人环境**
TRSS-Yunzai 3.1.0
Clash 开放127.0.0.1:7890代理服务
未开Clash的TUN模式

**Comment by Denfenglai** [comment]
建议给Discord适配器发issues
