### ISSUE TITLE
帮助生成的图片错误

### ISSUE THREAD

**Issue by PilotSherlock** [yeyang52/yenai-plugin#8]
![image](https://user-images.githubusercontent.com/42969918/210465051-dd5e7ac1-870a-490e-81ec-416fb90ab707.png)
![image](https://user-images.githubusercontent.com/42969918/210465057-0c58cf8f-1932-499b-abd5-099fd4fc5a54.png)

**Comment by yeyang52** [comment]
请检查puppeteer是否正常
