### ISSUE TITLE
trss云崽下群功能无法使用

### ISSUE THREAD

**Issue by liuzj288** [yeyang52/yenai-plugin#81]
**问题描述**
请简要描述您遇到的问题。

**Yunzai版本**
Miao-Yunzai

**如何复现**
请详细描述如何复现问题，步骤越详细越好。

1. 打开 '...'
2. 点击 '....'
3. 滚动到 '....'
4. 出现错误

**期望结果**
请简要描述您期望得到的结果。

**实际结果**
请简要描述您实际得到的结果。

**截图**
如果可以，请提供相关截图以帮助解释您的问题。

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

![image](https://github.com/yeyang52/yenai-plugin/assets/13833404/b654670b-9fe1-42c9-8768-5fc47249f095)

![image](https://github.com/yeyang52/yenai-plugin/assets/13833404/19fdc57a-521a-4e29-89f1-04c2d87fb5a1)

**Comment by Denfenglai** [comment]
早已修复
