### ISSUE TITLE
无法设置违禁词

### ISSUE THREAD

**Issue by LINKlang** [yeyang52/yenai-plugin#84]
**问题描述**
无法设置违禁词

**Yunzai版本**
trss-Yunzai

**如何复现**
请详细描述如何复现问题，步骤越详细越好。

命令：#新增精确撤违禁词6
或任何添加违禁词命令

**期望结果**
添加成功违禁词

**实际结果**
后台报错136:14无法读取null，qq不输出文字

**截图**
![image](https://github.com/yeyang52/yenai-plugin/assets/116951234/dd0e9fd0-61f9-449a-bdb6-8e72fa398a32)

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by Denfenglai** [comment]
问题测试后不存在异常，如果未解决请重新打开issue
